name: strainflye
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python >= 3.7
    - numpy
    - cython >= 0.29.12
    - samtools >= 1.7
    - minimap2 >= 2.17
    - prodigal
    # pysamstats requires pysam < 0.16, as of writing
    - pysam < 0.16
    - pysamstats
    - pip
