name: strainflye
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    # HACK to accommodate pysam / pysamstats for now -- see
    # https://github.com/fedarko/strainFlye/issues/8
    - python >= 3.6, <= 3.7
    - pip
    - numpy
    - samtools >= 1.7
    # Probably a later version will be installed; this is just the minimap2
    # version that added the asm20 preset. (If we want to use the more recently
    # added hifi preset, then we'd need to use >= 2.19 here.)
    - minimap2 >= 2.10
    # pysamstats requires pysam < 0.16, as of writing.
    # also, we install pysam(stats) via conda, rather than pip, to simplify
    # installation (making it easier for pysam to "see" samtools) --
    # https://stackoverflow.com/a/60197930
    - pysam < 0.16
    - pysamstats
    - prodigal
