name: strainflye
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    # HACK to accommodate pysam / pysamstats for now -- see
    # https://github.com/fedarko/strainFlye/issues/8
    - python >= 3.6, <= 3.7

    # Based on what pysam and pysamstats use currently -- see
    # https://github.com/pysam-developers/pysam/blob/master/requirements.txt
    - cython >= 0.29.12

    - pip

    - numpy

    # The main thing we use scipy for as of writing is scipy.special.comb();
    # v1.0 is the version of scipy that deprecated using scipy.misc.comb().
    # (This isn't a hard requirement, though.)
    - scipy >= 1.0

    - samtools >= 1.7

    - bcftools

    # Probably a later version will be installed; this is just the minimap2
    # version that added the asm20 preset. (If we want to use the more recently
    # added hifi preset, then we'd need to use >= 2.19 here.)
    - minimap2 >= 2.10

    # pysamstats requires pysam < 0.16, as of writing.
    # the > 0.15 pin was added to fix the build -- otherwise, conda would
    # install a really old pysam vsn (github.com/fedarko/strainFlye/issues/66)
    # also, we install pysam(stats) via conda, rather than pip, to simplify
    # installation (making it easier for pysam to "see" samtools) --
    # https://stackoverflow.com/a/60197930
    - pysam > 0.15, < 0.16

    - pysamstats

    - prodigal

    # Installing this with pip gives errors (at least as of Summer 2023), so we
    # include it here to fix the build
    - scikit-bio >= 0.5.8
