name: strainflye
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python >= 3.7
    - numpy
    - cython >= 0.29.12
    - samtools >= 1.7
    - minimap2 >= 2.17
    - prodigal
    # pysamstats requires pysam < 0.16, as of writing.
    # also, we install pysam(stats) via conda, rather than pip, to simplify
    # installation (making it easier for pysam to "see" samtools) --
    # https://stackoverflow.com/a/60197930
    #- pysam < 0.16
    #- pysamstats
    - pip
