# Based roughly on the main.yml and standalone.yml workflows in
# https://github.com/biocore/empress/blob/master/.github/workflows/,
# and on https://docs.github.com/en/actions/quickstart
name: strainFlye CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/conda-incubator/setup-miniconda#example-3-other-options
      - name: Install conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: strainflye
          environment-file: environment.yml
          python-version: 3.8

      - name: Install pysam(stats), also
        run: conda install "pysam < 0.16" pysamstats

      - name: Install strainFlye
        run: pip install -e .[dev]

      - name: Lint and stylecheck
        run: make stylecheck

      - name: Run tests
        run: make test

      - name: Upload code coverage information to Codecov
        uses: codecov/codecov-action@v2
