# Based roughly on the main.yml and standalone.yml workflows in
# https://github.com/biocore/empress/blob/master/.github/workflows/,
# and on https://docs.github.com/en/actions/quickstart
name: strainFlye CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    # Test on multiple python versions -- same as pysamstats' GH Actions YAML
    # file, as of writing --
    # https://github.com/alimanfoo/pysamstats/blob/master/.github/workflows/python-package.yml
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:

      # Updating from v2 to v3 to match, as of writing,
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Check out code
        uses: actions/checkout@v3

      # https://github.com/conda-incubator/setup-miniconda#example-3-other-options
      - name: Install conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: strainflye
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Install strainFlye (and pip dependencies)
        run: pip install -e .[dev]

      - name: Lint and stylecheck
        run: make stylecheck

      - name: Run tests
        run: make test

      - name: Upload code coverage information to Codecov
        uses: codecov/codecov-action@v2
